# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"  # Exclude pre-releases

name: Create Release

jobs:
    build:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: archon ${{ github.ref }}
                  body:
                  draft: false
                  prerelease: false

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pep517
            - name: Build package
              run: |
                python -m pep517.build --source --binary --out-dir dist/ .
            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                  user: __token__
                  password: ${{ secrets.pypi_password }}
